sequenceDiagram 
    actor utente as Unità Didattica
    participant script as script.js
    participant gestore as GestoreRichieste.php
    participant interfaccia as InterfacciaGrafica.php

    utente->>script: L'utente clicca<br/>il tasto 'Apri Prospetti'
    script->>script: Validazione input
    script->>gestore: POST action='Invia'<br/>matricole, CdL, data

    gestore->>interfaccia: ApriProspetti(cdl)
    interfaccia->>interfaccia: Verifico la presenza<br/>del file 'commissione.pdf'
    alt Se il file 'commissione.pdf' non esiste
        interfaccia->>utente: Mostra "Nessun prospetto da aprire per questo CdL" 
    end 

    interfaccia->>script: '/Laureandosi-Unipi-Project/prospetti/' . $cdl . '/commissione.pdf'

    script->>utente: I prospetti vengono<br/>aperti in una nuova scheda
    script->>script: Resetto il form
